### PR TITLE
make build reproducible

### PR DESCRIPTION
**Pull request by hboutemy**
see https://maven.apache.org/guides/mini/guide-reproducible-builds.html

you can confirm that the build is reproducible by simply executing
```
mvn clean install
mvn clean package artifact:compare
```

### CODE REVIEW

**Review by joedragons — APPROVED** [review]
I didn't test this, so if you want that, grain of salt my approval.

**Comment by bhamail** [comment]
Tried it out, and seems to be a time stamp difference still:

```shell
$ ~/devtools/apache-maven-3.8.4/bin/mvn clean install
...
$ ~/devtools/apache-maven-3.8.4/bin/mvn clean package artifact:compare
...
$ diffoscope target/reference/nexus-format-archetype-1.0.56-SNAPSHOT.jar target/nexus-format-archetype-1.0.56-SNAPSHOT.jar
--- target/reference/nexus-format-archetype-1.0.56-SNAPSHOT.jar
+++ target/nexus-format-archetype-1.0.56-SNAPSHOT.jar
├── zipinfo {}
│ @@ -1,8 +1,8 @@
│ -Zip file size: 61155 bytes, number of entries: 89
│ +Zip file size: 61156 bytes, number of entries: 89
│  drwxr-xr-x  2.0 unx        0 b- stor 22-Feb-03 11:18 META-INF/
│  -rw-r--r--  2.0 unx      133 b- defN 22-Feb-03 11:18 META-INF/MANIFEST.MF
│  drwxr-xr-x  2.0 unx        0 b- stor 22-Feb-03 11:18 META-INF/maven/
│  drwxr-xr-x  2.0 unx        0 b- stor 22-Feb-03 11:18 archetype-resources/
│  drwxr-xr-x  2.0 unx        0 b- stor 22-Feb-03 11:18 archetype-resources/docs/
│  drwxr-xr-x  2.0 unx        0 b- stor 22-Feb-03 11:18 archetype-resources/__rootArtifactId__/
│  drwxr-xr-x  2.0 unx        0 b- stor 22-Feb-03 11:18 archetype-resources/__rootArtifactId__/src/
│ @@ -84,8 +84,8 @@
│  -rw-r--r--  2.0 unx     1923 b- defN 22-Feb-03 11:18 archetype-resources/.circleci/config.yml
│  -rw-r--r--  2.0 unx      468 b- defN 22-Feb-03 11:18 archetype-resources/.circleci/.maven.xml
│  -rw-r--r--  2.0 unx     3279 b- defN 22-Feb-03 11:18 archetype-resources/SECURITY.md
│  ?rwsrwsrwt  2.0 unx        0 b- stor 22-Feb-03 11:18 META-INF/maven/org.sonatype.nexus.archetypes/
│  ?rwsrwsrwt  2.0 unx        0 b- stor 22-Feb-03 11:18 META-INF/maven/org.sonatype.nexus.archetypes/nexus-format-archetype/
│  -rw-r--r--  2.0 unx     9412 b- defN 22-Feb-03 11:14 META-INF/maven/org.sonatype.nexus.archetypes/nexus-format-archetype/pom.xml
│  -rw-r--r--  2.0 unx      146 b- defN 22-Feb-03 11:18 META-INF/maven/org.sonatype.nexus.archetypes/nexus-format-archetype/pom.properties
│ -89 files, 111035 bytes uncompressed, 41133 bytes compressed:  63.0%
│ +89 files, 111035 bytes uncompressed, 41134 bytes compressed:  63.0%
├── META-INF/maven/org.sonatype.nexus.archetypes/nexus-format-archetype/pom.properties
│ @@ -1,5 +1,5 @@
│  #Generated by Maven
│ -#Thu Feb 03 11:18:51 EST 2022
│ +#Thu Feb 03 11:18:56 EST 2022
│  version=1.0.56-SNAPSHOT
│  groupId=org.sonatype.nexus.archetypes
│  artifactId=nexus-format-archetype

```

I'm on a Mac, building with JDK 1.8.0_221

**Comment by hboutemy** [comment]
strange
can you check which version of maven-jar-plugin is used during the build?
you should get `--- maven-jar-plugin:3.2.2:jar (default-jar) @ nexus-format-archetype ---`, and that version of the plugin should not create such a pom.properties with a timestamp in it

**Comment by bhamail** [comment]
Yikes! Aaaaand, I ain't too bright. Everything works perfectly if I build using the correct branch. Doh!!!

**Pull request merged**
